export const cardsData = [
  {
    date: '20 July 2024 03:25pm',
    type: 'Transfer',
    description: 'Service Fee',
    amount: '$560',
    status: 'Credit',
    statusClass: 'bg-success-subtle text-success',
  },
  {
    date: '15 July 2024 12:35pm',
    type: 'Card Payment',
    description: 'UI/UX Project',
    amount: '$700',
    status: 'Debit',
    statusClass: 'bg-danger-subtle text-danger',
  },
  {
    date: '12 July 2024 10:05am',
    type: 'Card Payment',
    description: 'Freelancer Fee',
    amount: '$980',
    status: 'Debit',
    statusClass: 'bg-danger-subtle text-danger',
  },
  {
    date: '30 June 2024 11:12pm',
    type: 'Transfer',
    description: 'Monthly SIP Plan',
    amount: '$250',
    status: 'Credit',
    statusClass: 'bg-success-subtle text-success',
  },
  {
    date: '19 June 2024 07:15pm',
    type: 'Card Payment',
    description: 'Hotel Booking',
    amount: '$430',
    status: 'Debit',
    statusClass: 'bg-danger-subtle text-danger',
  },
  {
    date: '05 June 2024 02:40pm',
    type: 'Card Payment',
    description: 'Server Subscription',
    amount: '$600',
    status: 'Credit',
    statusClass: 'bg-success-subtle text-success',
  },
]
